# Generated by Django 3.1 on 2026-01-15 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalPrompt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('gratitude', 'Gratitude'), ('reflection', 'Self-Reflection'), ('goal', 'Goal Setting'), ('challenge', 'Challenges'), ('creative', 'Creative Writing'), ('mindfulness', 'Mindfulness')], max_length=20)),
                ('prompt_text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='JournalStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_entries', models.IntegerField(default=0)),
                ('total_words', models.IntegerField(default=0)),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('mood_distribution', models.JSONField(default=dict)),
                ('last_entry_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='journal_stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Journal Entry')),
                ('mood', models.CharField(choices=[('happy', '😊 Happy'), ('neutral', '😐 Neutral'), ('sad', '😔 Sad'), ('excited', '🤩 Excited'), ('calm', '😌 Calm'), ('grateful', '🙏 Grateful'), ('motivated', '💪 Motivated'), ('tired', '😴 Tired'), ('stressed', '😫 Stressed'), ('relaxed', '😎 Relaxed')], default='neutral', max_length=20)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('tags', models.TextField(blank=True, help_text='Store tags as JSON array')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('word_count', models.IntegerField(default=0)),
                ('entry_type', models.CharField(choices=[('daily', 'Daily Reflection'), ('gratitude', 'Gratitude Log'), ('goal', 'Goal Setting'), ('challenge', 'Challenge'), ('achievement', 'Achievement'), ('random', 'Random Thought')], default='daily', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HabitJournalLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.habit')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.journalentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['user', '-date'], name='Home_journa_user_id_efcf29_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['user', 'mood'], name='Home_journa_user_id_939626_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='habitjournallink',
            unique_together={('habit', 'journal_entry')},
        ),
    ]
