# Generated by Django 3.1 on 2026-01-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20260115_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitrecord',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
