# Generated by Django 3.1 on 2026-01-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_habitrecord_duration_minutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitrecord',
            name='duration_minutes',
        ),
        migrations.AddField(
            model_name='habitrecord',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='habitrecord',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habitrecord',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
